kind: pipeline
type: docker
name: publish-packages

steps:  
  - name: publish-packages
    image: node:23-slim
    environment:
      NODE_AUTH_TOKEN:
        from_secret: npm_token 
      NPM_EMAIL: rockie@kitmi.com.au
      COREPACK_ENABLE_AUTO_PIN: 0
    commands:
      - corepack enable      
      - echo registry=https://registry.npmjs.org/ >> .npmrc
      - echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> .npmrc
      - echo email=$NPM_EMAIL >> .npmrc
      - echo always-auth=true >> .npmrc      
      - pnpm config get registry
      - pnpm i
      - pnpm build
      - pnpm release-all      

trigger:
  branch:
    - publish
  event:
    - push