#!/usr/bin/env node

import fs from 'fs-extra'
import { globSync } from 'glob';

// 1. Move docs generated by jsdoc
// 1.1 read package.json
const pkg = fs.readJsonSync('./package.json');
const { name, version } = pkg;

// 1.2 scan docs/<package name> folder for subfolders only

const docDir = `./docs/${name}`;
if (fs.pathExistsSync(docDir) === false) {
    console.warn('No new docs found');
    process.exit(1);
}   

const docVersionDir = `${docDir}/${version}`;
if (fs.pathExistsSync(docVersionDir) === false) {
    console.warn('No new docs found');
    process.exit(1);
}   

const subDirs = globSync(docDir + '/*', { onlyDirectories: true });

// 1.3 remove all subfolders in docs/<package name> except docs/<package name>/<version>

subDirs.forEach((subDir) => {    
    if (`./${subDir}` !== docVersionDir) {
        fs.removeSync(subDir);
    }
});

// 1.4 remove docs/mannual and move docs/<package name>/<version> to docs/mannual

fs.removeSync('./docs/manual');
fs.moveSync(docVersionDir, './docs/manual');
fs.removeSync(docDir.split('/').slice(0, -1).join('/'));

console.log('Docs generated by jsdoc moved to docs/manual');
